FROM python:3.8

# ARG DISCORD_TOKEN
# ARG DISCORD_GUILD
# ARG GOOGLE_API_KEY
# ARG CREDENTIALS_JSON

# ENV DISCORD_TOKEN=${DISCORD_TOKEN}
# ENV DISCORD_GUILD=${DISCORD_GUILD}
# ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}
# ENV CREDENTIALS_JSON=${CREDENTIALS_JSON}

COPY requirements.txt .

RUN pip3 install -r requirements.txt


WORKDIR /bot


COPY ./src .


CMD ["python3", "start.py"]
