version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys

      - run:
        name: Connect to VPS
        command: ssh root@108.61.193.108