version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: ls
      - run: echo "Building image"
      - run: docker build -t chshsmit/discord-music:latest .
      - run: echo "Authenticating with Docker Hub"
      - run: docker login --username chshsmit --password $DOCKERHUB_PASSWORD
      - run: docker push chshsmit/discord-music:latest