version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker

      - run:
        name: Building Image
        command: docker build -t chshsmit/discord-music:latest .

      - run:
        name: Authenticate with Docker Hub
        command: docker login --username chshsmit --password $DOCKERHUB_PASSWORD

      - run:
        name: Push Image
        command: docker push chshsmit/discord-music:latest

      - run:
        name: Connect to VPS
        command: ssh root@108.61.193.108 << 'ENDSSH'

