version: 2.0
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys

      - run: docker build -t chshsmit/discord-music:latest .

      - run: docker login --username chshsmit --password $DOCKERHUB_PASSWORD

      - run: docker push chshsmit/discord-music:latest

      - run: ssh-keyscan -H 108.61.193.108 >> ~/.ssh/known_hosts

      - run: |
          ssh root@108.61.193.108 << 'ENDSSH'
          docker login --username chshsmit --password $DOCKERHUB_PASSWORD
          docker pull chshsmit/discord-music:latest
          docker run \
              --name discord-music \
              -e DISCORD_TOKEN=$DISCORD_TOKEN \
              -e DISCORD_GUILD=$DISCORD_GUILD \
              -e GOOGLE_API_KEY=$GOOGLE_API_KEY \
              -e CREDENTIALS_JSON=$CREDENTIALS_JSON \
              -d chshsmit/discord-music:latest \

          ENDSSH
